# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{smirk}
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["James Miller"]
  s.date = %q{2010-02-10}
  s.description = %q{Smirk is a simple Ruby wrapper for the SmugMug 1.2.2 API specification. It currently supports initiating a session, finding albums, images, and categories.}
  s.email = %q{james@jk-tech.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/smirk.rb",
     "lib/smirk/client.rb",
     "lib/smirk/album.rb",
     "lib/smirk/image.rb",
     "lib/smirk/category.rb",
     "test/helper.rb",
     "test/test_smirk.rb"
  ]
  s.homepage = %q{http://github.com/bensie/smirk}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby wrapper for the SmugMug API}
  s.test_files = [
    "test/helper.rb",
     "test/test_smirk.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<rest-client>, ["~> 1.2.0"])
      s.add_runtime_dependency(%q<json>, ["~> 1.2.0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rest-client>, ["~> 1.2.0"])
      s.add_dependency(%q<json>, ["~> 1.2.0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rest-client>, ["~> 1.2.0"])
    s.add_dependency(%q<json>, ["~> 1.2.0"])
  end
end

